/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.inventory.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFB70054)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE2116C)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFFA73359)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFE779D)
val onSecondaryContainerLight = Color(0xFF740635)
val tertiaryLight = Color(0xFFA93200)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD34000)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF27171B)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF27171B)
val surfaceVariantLight = Color(0xFFFFD9E0)
val onSurfaceVariantLight = Color(0xFF5B3F45)
val outlineLight = Color(0xFF8F6F75)
val outlineVariantLight = Color(0xFFE3BDC4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3E2B2F)
val inverseOnSurfaceLight = Color(0xFFFFECEF)
val inversePrimaryLight = Color(0xFFFFB1C2)
val surfaceDimLight = Color(0xFFF1D3D8)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F2)
val surfaceContainerLight = Color(0xFFFFE8EC)
val surfaceContainerHighLight = Color(0xFFFFE1E6)
val surfaceContainerHighestLight = Color(0xFFF9DBE0)

val primaryLightMediumContrast = Color(0xFF700031)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFD60064)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF700231)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFFBA4267)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF671B00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFC63C00)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F7)
val onBackgroundLightMediumContrast = Color(0xFF27171B)
val surfaceLightMediumContrast = Color(0xFFFFF8F7)
val onSurfaceLightMediumContrast = Color(0xFF1C0D10)
val surfaceVariantLightMediumContrast = Color(0xFFFFD9E0)
val onSurfaceVariantLightMediumContrast = Color(0xFF492F35)
val outlineLightMediumContrast = Color(0xFF674B51)
val outlineVariantLightMediumContrast = Color(0xFF84656B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF3E2B2F)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFECEF)
val inversePrimaryLightMediumContrast = Color(0xFFFFB1C2)
val surfaceDimLightMediumContrast = Color(0xFFDCBFC4)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0F2)
val surfaceContainerLightMediumContrast = Color(0xFFFFE1E6)
val surfaceContainerHighLightMediumContrast = Color(0xFFF3D6DA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE8CACF)

val primaryLightHighContrast = Color(0xFF5E0028)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF940043)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF5E0028)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF8A1C44)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF561500)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF882600)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F7)
val onBackgroundLightHighContrast = Color(0xFF27171B)
val surfaceLightHighContrast = Color(0xFFFFF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFFFD9E0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF3E252B)
val outlineVariantLightHighContrast = Color(0xFF5D4248)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF3E2B2F)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFB1C2)
val surfaceDimLightHighContrast = Color(0xFFCEB2B7)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFECEF)
val surfaceContainerLightHighContrast = Color(0xFFF9DBE0)
val surfaceContainerHighLightHighContrast = Color(0xFFEBCDD2)
val surfaceContainerHighestLightHighContrast = Color(0xFFDCBFC4)

val primaryDark = Color(0xFFFFB1C2)
val onPrimaryDark = Color(0xFF66002C)
val primaryContainerDark = Color(0xFFFF4B88)
val onPrimaryContainerDark = Color(0xFF1F0008)
val secondaryDark = Color(0xFFFFB1C2)
val onSecondaryDark = Color(0xFF66002C)
val secondaryContainerDark = Color(0xFF871942)
val onSecondaryContainerDark = Color(0xFFFF96B0)
val tertiaryDark = Color(0xFFFFB59E)
val onTertiaryDark = Color(0xFF5D1800)
val tertiaryContainerDark = Color(0xFFFC5A1E)
val onTertiaryContainerDark = Color(0xFF1C0300)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1E0F13)
val onBackgroundDark = Color(0xFFF9DBE0)
val surfaceDark = Color(0xFF1E0F13)
val onSurfaceDark = Color(0xFFF9DBE0)
val surfaceVariantDark = Color(0xFF5B3F45)
val onSurfaceVariantDark = Color(0xFFE3BDC4)
val outlineDark = Color(0xFFAA888F)
val outlineVariantDark = Color(0xFF5B3F45)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF9DBE0)
val inverseOnSurfaceDark = Color(0xFF3E2B2F)
val inversePrimaryDark = Color(0xFFBB0057)
val surfaceDimDark = Color(0xFF1E0F13)
val surfaceBrightDark = Color(0xFF473438)
val surfaceContainerLowestDark = Color(0xFF180A0D)
val surfaceContainerLowDark = Color(0xFF27171B)
val surfaceContainerDark = Color(0xFF2C1B1F)
val surfaceContainerHighDark = Color(0xFF372529)
val surfaceContainerHighestDark = Color(0xFF433034)

val primaryDarkMediumContrast = Color(0xFFFFD1D9)
val onPrimaryDarkMediumContrast = Color(0xFF520022)
val primaryContainerDarkMediumContrast = Color(0xFFFF4B88)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFD1D9)
val onSecondaryDarkMediumContrast = Color(0xFF520022)
val secondaryContainerDarkMediumContrast = Color(0xFFE7658B)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD3C5)
val onTertiaryDarkMediumContrast = Color(0xFF4B1100)
val tertiaryContainerDarkMediumContrast = Color(0xFFFC5A1E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1E0F13)
val onBackgroundDarkMediumContrast = Color(0xFFF9DBE0)
val surfaceDarkMediumContrast = Color(0xFF1E0F13)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF5B3F45)
val onSurfaceVariantDarkMediumContrast = Color(0xFFFAD2DA)
val outlineDarkMediumContrast = Color(0xFFCDA9AF)
val outlineVariantDarkMediumContrast = Color(0xFFAA888E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF9DBE0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF372529)
val inversePrimaryDarkMediumContrast = Color(0xFF910042)
val surfaceDimDarkMediumContrast = Color(0xFF1E0F13)
val surfaceBrightDarkMediumContrast = Color(0xFF543F43)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF100407)
val surfaceContainerLowDarkMediumContrast = Color(0xFF2A191D)
val surfaceContainerDarkMediumContrast = Color(0xFF352327)
val surfaceContainerHighDarkMediumContrast = Color(0xFF402E31)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF4C383C)

val primaryDarkHighContrast = Color(0xFFFFEBEE)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFABBE)
val onPrimaryContainerDarkHighContrast = Color(0xFF1F0008)
val secondaryDarkHighContrast = Color(0xFFFFEBEE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFABBE)
val onSecondaryContainerDarkHighContrast = Color(0xFF210009)
val tertiaryDarkHighContrast = Color(0xFFFFECE7)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFAF96)
val onTertiaryContainerDarkHighContrast = Color(0xFF1C0300)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF1E0F13)
val onBackgroundDarkHighContrast = Color(0xFFF9DBE0)
val surfaceDarkHighContrast = Color(0xFF1E0F13)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF5B3F45)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFFEBEE)
val outlineVariantDarkHighContrast = Color(0xFFDFB9C0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF9DBE0)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF910042)
val surfaceDimDarkHighContrast = Color(0xFF1E0F13)
val surfaceBrightDarkHighContrast = Color(0xFF604B4F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF2C1B1F)
val surfaceContainerDarkHighContrast = Color(0xFF3E2B2F)
val surfaceContainerHighDarkHighContrast = Color(0xFF4A363A)
val surfaceContainerHighestDarkHighContrast = Color(0xFF564145)

